apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/postgresql.mlflow: ""
  name: postgresql
  namespace: mlflow
spec:
  channel: v5
  installPlanApproval: Automatic
  name: postgresql
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: postgresoperator.v5.8.2
